
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "DIVIDE ID LPAREN MINUS NEWLINE NUMBER PLUS RPAREN TIMESstatement : expressionexpression : expression '+' expression\n                  | expression '-' expression\n                  | expression '*' expression\n                  | expression '/' expressionexpression : NUMBER"
    
_lr_action_items = {'NUMBER':([0,4,5,6,7,],[3,3,3,3,3,]),'$end':([1,2,3,8,9,10,11,],[0,-1,-6,-2,-3,-4,-5,]),'+':([2,3,8,9,10,11,],[4,-6,4,4,4,4,]),'-':([2,3,8,9,10,11,],[5,-6,5,5,5,5,]),'*':([2,3,8,9,10,11,],[6,-6,6,6,6,6,]),'/':([2,3,8,9,10,11,],[7,-6,7,7,7,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,6,7,],[2,8,9,10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','parser.py',4),
  ('expression -> expression + expression','expression',3,'p_expression_binop','parser.py',8),
  ('expression -> expression - expression','expression',3,'p_expression_binop','parser.py',9),
  ('expression -> expression * expression','expression',3,'p_expression_binop','parser.py',10),
  ('expression -> expression / expression','expression',3,'p_expression_binop','parser.py',11),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',15),
]
